Add simple test for container

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,31 +1,46 @@
-name: Build and Push Docker Image
+name: Docker
 
 on:
   push:
     branches: [ main ]
+  pull_request:
+    branches: [ main ]
 
 jobs:
   build:
+
     runs-on: ubuntu-latest
+
     steps:
-      - uses: actions/checkout@v3
-      - name: Login to DockerHub
-        uses: docker/login-action@v2 
-        with:
-          username: ${{ secrets.DOCKER_HUB_USERNAME }}
-          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v3
-        with:
-          context: .
-          push: true
-          tags: donchenko/tgdefbot:latest
-          build-args: |
-            TOKEN=${{ secrets.TOKEN }}
-            MERRIAM_WEBSTER_API_KEY=${{ secrets.MERRIAM_WEBSTER_API_KEY }}
-      - name: Notify Telegram
-        uses: appleboy/telegram-action@master
-        with:
-          to: 59666312
-          token: ${{ secrets.TOKEN }}
-          message: "Build completed successfully"
+    - uses: actions/checkout@v2
+
+    - name: Login to DockerHub
+      uses: docker/login-action@v1 
+      with:
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+    - name: Build and push
+      id: docker_build
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        push: false
+        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tgdefbot:latest
+
+    - name: Run and check the container
+      run: |
+        docker run --rm -d --name test_container ${{ secrets.DOCKERHUB_USERNAME }}/tgdefbot:latest
+        sleep 10
+        if docker logs test_container | grep "Starting the bot"; then
+          echo "Container started successfully"
+        else
+          echo "Container failed to start" && exit 1
+        fi
+
+    - name: Push to DockerHub
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        push: true
+        tags: ${{ secrets.DOCKERHUB_USERNAME }}/tgdefbot:latest
